name: Docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Required for gh-pages deployment with GITHUB_TOKEN
permissions:
  contents: write

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build MkDocs site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up uv
        uses: astral-sh/setup-uv@v3

      - name: Sync dependencies (dev)
        run: uv sync --group dev

      - name: Build docs (strict)
        run: uv run mkdocs build --strict

      - name: Upload site artifact (PR previews)
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: mkdocs-site
          path: site
          if-no-files-found: error

  deploy:
    name: Deploy to GitHub Pages (gh-pages)
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up uv
        uses: astral-sh/setup-uv@v3

      - name: Sync dependencies (dev)
        run: uv sync --group dev

      - name: Build docs (strict)
        run: uv run mkdocs build --strict

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          keep_files: true  # preserve existing files like CNAME if present
